### ISSUE TITLE
Move builder activation to builder_enabled flag

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10187]
1. [x] Remove `builder_enabled` box toggle, via #10067
 2. [x] Add `builder_enabled` to Organization model, and set NOT NULL, via #10188
 3. [x] Disable builder FF for users with disabled builder. In the box create a listing `Carto::User.where(builder_enabled: false).select(&:builder_enabled?)` and disable flag in Central.
 4. [x] Start accepting `builder_enabled` updates from Central, via #10190
 5. [x] Copy the values from FF, `Carto::User.find_each { |u| u.update_column(:builder_enabled, u.builder_enabled?) }` (this will disable the builder for anyone who doesn't have the FF set).
 6. [x] Update User model functions to stop reading the FF and just check the attribute instead, via #10189 
 7. [x] Make Central stop setting the FF (now it is being copied from the attribute on save). via CartoDB/cartodb-central#1530
 8. [x] Remove feature flag

**Note**: Currently `builder_enabled?` is a method that checks the FF, `builder_enabled` is the attribute.

**Comment by javitonino** [comment]
Please review the plan @CartoDB/builder-backend. Just the plan for now, I'll ask for CRs later (I got lots of specs to fix yet).

**Comment by juanignaciosl** [comment]
- How come removing `builder_enabled` flag is the first step? To block people from changing it?
- I don't get step 5. Maybe the "Copy the values from FF" is not actually present in the code snippet?

Both question are probably trivial.

This is what I understand: steps 1-5 are meant to "move" the setting value from the FF to the actual flag, 6-7 the setting logic, and 8 is cleanup. Am I right?

**Comment by javitonino** [comment]
- Just from the UI. Yes, we want Central to be the authoritative source for builder_enabled, not the user. And we are not syncing from the box to central. So I think the best way is to disable the option to change this before syncing.
 - That code snippet is setting builder_enabled attribute from the feature flag (which is `builder_enabled?` ending in `?`).

And you are right about that steps, that is roughly the idea.

**Comment by javitonino** [comment]
I merged all this stuff together at the `all_toggle_stuff` branch and tested it (staging cloud). After some minor adjustments here and there, it seems to be working, so I'll start calling CRs on Monday. Meanwhile, have a nice weekend!

**Comment by javitonino** [comment]
This is ready except for removing the FF. I'm leaving it there for a few more days because I'm a coward. Leaving this ticket open as a reminder, but it is essentially done.

**Comment by juanignaciosl** [comment]
🐔 



_(just kidding)_
