### ISSUE TITLE
AutoStyle feature

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10255]
- [x] Represent auto-style in the Builder side (#8551).
- [x] Auto style on category widget doesn't get the legend refreshed (#10118).
- [x] Autostyle color picker on widgets options (#9872).
- [x] Expand widget definition with new style things.
  - Including backend changes (https://github.com/CartoDB/cartodb/issues/10252).
- [x] Remove AutoStyle button when an aggregation style is applied (#8468).
  - AutoStyle check should be disabled in that case.
- [x] Change widget type should "take" previous auto_style and widget_style properties.
- [x] ~~When widget column has changed, custom AutoStyle should be reseted if it was enabled~~.
- [x] Check if Time-series could manage auto-style: applying only proper color.
- [x] Add new options in the widget model (Deep-insights).
  - [x] Delete widget (https://github.com/CartoDB/deep-insights.js/issues/452).
  - [x] Edit widget (https://github.com/CartoDB/cartodb/issues/8003).
- [x] Hide quantification and bins from the fill component.
- [x] Disable auto-style if widget is removed (#10408).
- [ ] Add all necessary tests.

**Comment by xavijam** [comment]
Definition: 

```json
{
	options: …
	style: {
		auto_style: {
			definition: {
				fill: {
					color: {
						attribute: 'segmentati',
						quantification: 'quantiles',
						range: ["#5B3F95", "#1D6996", "#129C63", "#73AF48", "#EDAD08", "#E17C05", "#C94034", "#BA0040", "#8E1966", "#6F3072", "#DC1721"]
					}
				}
			},
			custom: true,
			allowed: true
		},
		widget_style: {
			definition: {
				fill: {
					color: {
						fixed: '#FFF'
					}
				}
			},
			custom: true,
			allowed: true
		}
	},
	…
}
```

**Comment by xavijam** [comment]
Definition for a histogram widget:

```js
{
    options: …
    style: {
        auto_style: {
            definition: {
                fill: {
                    color: {
                        attribute: 'cartodb_id',
                        quantification: 'quantiles',
                        bins: 3,
                        range: ["#5B3F95", "#1D6996", "#129C63"]
                    }
                }
            },
            custom: true,
            allowed: true
        },
        widget_style: {
            definition: {
                fill: {
                    color: {
                        fixed: '#FFF'
                    }
                }
            }
        }
    },
    …
}
```

**Comment by xavijam** [comment]
Closing this ticket in favor of https://github.com/CartoDB/cartodb/issues/10420.
