### ISSUE TITLE
Icon styling on the Fill component (waiting for cartodb-platform/issues/2764) [DON'T DEPLOY UNTIL 12/13]

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#10746]
This feature enables the styling with icons in Builder through the Fill component.

Design: https://github.com/CartoDB/cartodb/issues/10452

PR (and information on how to test it): https://github.com/CartoDB/cartodb/pull/11005

### Implemented
- [x] Add actual icon in the input field (#10852)
- [x] Create flag for the feature (#10847) (`icon-styling`)
- [x] Use an image and a color on the img/color row.
- [x] Add image pane inside the Solid Pane
- [x] Add Img / color row 
- [x] Update CartoCSS.
- [x] Added basic image pane
- [x] Show assets in the modal.
- [x] Add modal to select the assets.
- [x] Create the assets collection to retrieve the assets from the backend
- [x] Add/fix specs (https://github.com/CartoDB/cartodb/issues/10875).
- [x] Add styles in the modal (@piensaenpixel)
- [x] Enable CORS for the assets bucket (https://github.com/CartoDB/cartodb-platform/issues/2764)

### Future features

- [ ] Add upload file system.
- [ ] Show patterns.
- [ ] Add [IMG] icon to the input fill.

**Comment by javierarce** [comment]
This feature depends on https://github.com/CartoDB/cartodb-platform/issues/2764
