### ISSUE TITLE
Integrate all new components in order to update the DO analysis UI

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11619]
Basically this should be the final ticket before closing [Data Observatory Analysis UI milestone](https://github.com/CartoDB/cartodb/milestone/135). It should integrate:

- [x] [Slider for DO boundaries](https://github.com/CartoDB/cartodb/issues/11617).
- [x] [Dropdown for DO measurament](https://github.com/CartoDB/cartodb/issues/11618).
- [ ] [Orchestrate all requests for a DO measurement](https://github.com/CartoDB/cartodb/issues/11802)
- [ ] [Add several "items" in the same (Backbone)Form](https://github.com/CartoDB/cartodb/issues/11621).
- [ ] [Questions about implementation](https://github.com/CartoDB/design/issues/620).

Main branch where pull request should apply : `data-observatory-analysis-ui`

And of course, it should work as it is described here: https://github.com/CartoDB/cartodb/issues/9991.

---
* Design: https://invis.io/5G9YKGISB

**Comment by xavijam** [comment]
It is gonna be blocked until all points described are done.

**Comment by nobuti** [comment]
Also, [here](https://github.com/CartoDB/cartodb/issues/11663) there is relevant information that is needed for this issue.

**Comment by jorgesancha** [comment]
Dependent on https://github.com/CartoDB/observatory-extension/issues/263

**Comment by noguerol** [comment]
The mockup has been updated: https://invis.io/5G9YKGISB with no "Bounding box" nor "global" options in the region dropdown. The first one has been discarded due to its cost, the second because we still don't have global measurements in DO.

**Comment by rafatower** [comment]
Posting here as I think this is the "master issue". This was blocked time ago but the original blockers are removed AFAIK.

Things are falling into place. But there's still a "known unknown" non-functional issue that I believe has to do with size of geometries and/or complexity validity. Fortunately we're able to reproduce it: https://github.com/CartoDB/cartodb-platform/issues/3081#issuecomment-302357552

**Comment by xavijam** [comment]
Closing because it is already being tackled in the main issue.
