### ISSUE TITLE
Pending issues from user migration (user and organization)

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12326]
We did some cheating to get user migrator out as soon as possible. We need to handle some missing stuff:

- [ ] Visualization
  - [x] Mapcaps (split to #12407)
  - [ ] DataImport models and friends (split to #12408)
  - [ ] Data library? (ExternalSource) (split to #12408)
  - [x] Mark as vizjson v2 (split to  #12407)
- [ ] User
  - [x] Received notifications
  - [x] Import viewers with visualizations
  - [x] Redis (dataservices usage, mapviews)
  - [ ] SearchTweets (requires exporting `data_imports`, might be complicated) (split to #12408)
- [x] Organizations
  - [x] Notifications
  - [x] Groups

**Comment by javitonino** [comment]
Closing this one since all subtasks are in their own issue.
