### ISSUE TITLE
Axis labels changes in Time-Series

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12658]
### Context
After several acceptance tests, a few things have to be changed regarding the axis labels. These issues were attached to the [out-of-bounds ticket](https://github.com/CartoDB/cartodb/issues/12480) because it was convenient to tackle them in that issue. Since that issue is now blocked, I move those minor issues to this ticket to be addressed on their own.

https://github.com/CartoDB/cartodb/issues/12480

### Subissues

Copypasting from those [comments](https://github.com/CartoDB/cartodb/issues/12088#issuecomment-321227542).

1
- [x] To prevent that overlapping its better to align the label not to the dragger but to the bin itself. I attach some mocks:

![image](https://user-images.githubusercontent.com/70603/29119302-e59bec76-7d05-11e7-88ab-2266ff422828.png)

![image](https://user-images.githubusercontent.com/70603/29119306-ea4b2fca-7d05-11e7-9f52-5288b34c7f6d.png)

2
- [x] Which drives us to a new bug, the cropped label on the time series limits:

![image](https://user-images.githubusercontent.com/70603/29119324-01ab5e38-7d06-11e7-8c29-d0255342d5aa.png)

3
- [x] I found this bug. We shouldn't be able to place the handle in the middle of the bucket. 

![bucket](https://user-images.githubusercontent.com/16247628/29168324-b417dc72-7dce-11e7-81cf-f6f5f33443b7.gif)

4
- [x] Lastly, when selecting only one bucket, we shouldn't display the value of that single bucket twice. There should only be one, above and in the middle of the bucket: 

![screen shot 2017-08-10 at 13 02 03](https://user-images.githubusercontent.com/16247628/29168377-e293b0b2-7dce-11e7-95b1-c4b73bf81f1e.png)

**Comment by ivanmalagon** [comment]
I have some concerns with this issues. Calling @CartoDB/design to get their point of view.

Regarding 1. It says to align the label to the bin instead of the handle.
This can make sense when dealing with dates but it doesn't when dealing with numeric columns: `this bin is Jan 2017` against `this bin goes from 130 to 256`.
To me, it feels very weird to have different behaviours depending on the column type, something that the user may not be aware of.

Number 4 is related. It says to align only one label if there's only one selected bin in a date column. That will move the labels from handles to bin and will make disappear one of them.

Your thoughts?

**Comment by ivanmalagon** [comment]
Blocked until Design approves the implementation.

**Comment by noguerol** [comment]
@CartoDB/design for acceptance

**Comment by arianaescobar** [comment]
We already did the acceptance last week, on Friday afternoon. Everything looked good. 

Regarding your concerns, @ivanmalagon. IMO I think we should move forward and test it.

**Comment by ivanmalagon** [comment]
Design Seal of Approval. Let's move to Code Review!

![image](https://user-images.githubusercontent.com/1078228/30370986-7d67d6f8-9879-11e7-8f4a-fe3a0ff58643.png)

**Comment by Jesus89** [comment]
It works as expected :star: Let's move to production!

**Comment by Jesus89** [comment]
:rocket:

**Comment by Jesus89** [comment]
Closed by #12766
