### ISSUE TITLE
Remove support for List widgets

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#12826]
Back in the old days, before BUILDER and [deep-insights.js](https://github.com/cartodb/deep-insights.js) were born, there was a type of widget known internally as the "List Widget". We implemented support for this widget across multiple components:

- [x] [CartoDB.js](https://github.com/cartodb/cartodb.js/tree/v4) -> [Issue](https://github.com/CartoDB/cartodb.js/issues/1756)
- [x] [deep-insights.js](https://github.com/cartodb/deep-insights.js) -> [Issue](https://github.com/CartoDB/deep-insights.js/issues/593)
- [x] [Windshaft-cartoDB](https://github.com/CartoDB/Windshaft-cartodb/) -> [PR](CartoDB/Windshaft-cartodb#763)

After talking to @noguerol, we agreed that we can safely remove the code related to this widget from all these components cause it doesn't look like it's going to be added to BUILDER in the near future.... 🔥 

Let's close this issue once each individual issue has been closed.

cc: @rochoa.

**Comment by rochoa** [comment]
About Windshaft-cartodb: https://github.com/CartoDB/Windshaft-cartodb/pull/763.
