### ISSUE TITLE
Preloaded maps in new accounts

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13116]
As part of the improvements in our onboarding process, we're adding [two awesome maps](https://github.com/CartoDB/design/issues/757) to every new account to showcase the capabilities of Builder from the get-go. 

We're still working on the maps but I wanted to open this ticket over here to give you all visibility that this is coming. Maybe we could even start the implementation and then just wait until we have the two final .carto files. 

[[Feature doc](https://docs.google.com/document/d/1VOtIOSGKevaA-DkgPkkX9s30eWdQn8pnG_Ck591Q4bY/edit#)]

**Comment by matallo** [comment]
yes yes yes!

**Comment by ramiroaznar** [comment]
:100:

**Comment by arianaescobar** [comment]
Issue update! 

## To-Do

- [ ] **Preload two maps to every new Builder account**

We have our first map: [Development.around.Union.Station.zip](https://github.com/CartoDB/cartodb/files/1578759/Development.around.Union.Station.zip) | @makella will have the second one ready soon!  

- [ ] **Update the initial onboarding tour** to reflect these preloaded maps

We'll share the changes as soon as we have them. 

- [ ] **Implement an A/B test for the signup process**, in which: 

**A:** After signup, users will be taken directly to the first map, without passing through Dashboard. 
**B:** After signup, users arrive in Dashboard, where they'll see our two preloaded maps. 

- [ ] **Measure the test** comparing the number of sessions and time spent per session for each test option (cc @msaenzde11 we have everything in place to measure this, right?)  

## Plan 

@juanignaciosl When do you think you guys could start working on this?

**Comment by juanignaciosl** [comment]
> @juanignaciosl When do you think you guys could start working on this?

End of January, if we're lucky U_U

cc @jorgesancha
