### ISSUE TITLE
[Dasboard][Onboarding] Create basic wizard for welcome section

### ISSUE THREAD

**Issue by csubira** [CartoDB/cartodb#14770]
### Define components

- [x] Create dialog component https://github.com/CartoDB/cartodb/issues/14782
- [x] Create wizard with quick steps https://github.com/CartoDB/cartodb/issues/14782
    - [x] Header -> breadcrumb
    - [x] Content
    - [x] Footer -> Next/Back buttons
- [x] Create components inside content section https://github.com/CartoDB/cartodb/issues/14783, https://github.com/CartoDB/cartodb/issues/14791
    - [x] Code components
    - [x] Iframe components
    - [x] Text components
    - [x] Image components
- [x] Create distributor component https://github.com/CartoDB/cartodb/issues/14793

### Decide where to store content https://github.com/CartoDB/cartodb/issues/14807
- [x] Divide different types of content (code, text, images)
- [x] Set webpack configuration to these assets as exceptions (i.e. code blocks)
- [x] Include content for CARTO VL https://github.com/CartoDB/cartodb/issues/14791, CARTOframes https://github.com/CartoDB/cartodb/issues/14807 and builder https://github.com/CartoDB/cartodb/issues/14817 wizard

### Decide plugin for code highlighter
- [x] Add package to highlight code

### Embedded live example 
- [x] List URLs for embedded example code and map (in final step) https://github.com/CartoDB/cartodb/pull/14821
~~- [ ] Create switch component~~

## Branch for this release
`dashboard-onboarding-dev`

## PR to be merged to master
https://github.com/CartoDB/cartodb/pull/14823

## Related tickets:
https://github.com/CartoDB/cartodb/issues/14783
https://github.com/CartoDB/cartodb/issues/14782
https://github.com/CartoDB/cartodb/issues/14793
https://github.com/CartoDB/cartodb/issues/14791
https://github.com/CartoDB/cartodb/issues/14817

**Comment by alonsogarciapablo** [comment]
@cillas @alejandraarri something to take into account here: we need to measure how users interact with this new component (eg: what percentage of users that get to the dashboard actually visit / complete each of the "wizards"). We will use Google Tag Manager and Google Analytics. In order to set this up, there are two options:

- Detect when an element becomes visible (using CSS selector).
- Detect changes in the "history" (URL).

So, we should either give a meaningful / unique "id" to each of the steps, or update the URL as the user navigates through the wizards.
