### ISSUE TITLE
[Dashboard] Add Data Observatory catalog - Implementation

### ISSUE THREAD

**Issue by csubira** [CartoDB/cartodb#15106]
## Context
https://github.com/CartoDB/product/issues/464

## Main tasks 
- [x] Structure: Create page and tabs component https://github.com/CartoDB/cartodb/issues/15114
- [x] Page: List datasets and filters https://github.com/CartoDB/cartodb/issues/15115
- [x] Interactivity: Implement working filters https://github.com/CartoDB/cartodb/issues/15116
- [x] Dataset Detail page https://github.com/CartoDB/cartodb/issues/15124
