### ISSUE TITLE
[BQ Connector] FDW feasibility

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15152]
We think that using  [bigquery_fdw](https://github.com/gabfl/bigquery_fdw) could be a promising way to implement a BigQuery connector in the Import API. Being written in Python it should be possible to modify it to use the [BQ Storage API](https://cloud.google.com/bigquery/docs/reference/storage/) for performance.

This task consists in testing and analysend this FDW to determine the feasibility of such modification, as well as the possibility of accommodating a different authentication method as determined in #15151

- [x] Test bigquery_fdw (done with PG 10.1)
- [ ] Test with PG 11 
- [ ] Test with PG 12
- [x] feasibility of changing authentication to use OAuth2
- [x] feasibility of using BQ Storage API
- [x] feasibility adding a query option
- [x] feasibility of implementing IMPORT FOREIGN SCHEMA

**Comment by jgoizueta** [comment]
So far I've tested this with PG 10.1 in linux. It uses the python interpreter in the libpython referenced by  multicorn (the multicorn extension has a binary multicorn.so linked to a libpython so). We need to use a Python 3 version for bigquery_fdw compatibility and to avoid problems with Python 2 EOL. Note that the python interpreter used here is thus independent of the one used by plpython. 

 Some caveats I've found to install it:
*  To use Python we just need to compile and install multicorn with an env var `PYTHON_OVERRIDE=python3` but beware of using `export` and then `sudo` (sudo must be used for `make install` to copy files to PG paths and to install Python 3 modules globally so they are accessible from PG).
  `PYTHON_OVERRIDE=python3 make && sudo PYTHON_OVERRIDE=python3 make install`
* The python module `bigquery_fdw` and all its dependencies must be available from the Python 3 environment for the postgres user, so beware of locally installed packages. If installing from a `bigquery_fdw` directory we can: `sudo pip3 install . --ignore-installed`

**Comment by jgoizueta** [comment]
Adding a query OPTION should not be a problem, since the query executed in BQ is constructed by the Python code. It's a matter of replacing the table by a subselect here:
https://github.com/CartoDB/bigquery_fdw/blob/38c32188266f412b76d79d77fdc30f23f4ad7bad/src/fdw.py#L259-L260

**Comment by rafatower** [comment]
Closing this, as I think it is not useful anymore. Please feel free to reopen if you think otherwise.
