### ISSUE TITLE
[connectors-ui] New UI for connectors - Basic

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15194]
### User Story
*As a* user
*I want* to have a way to connect to many different data sources (more than the currently displayed)
*So that* I can work with my own data easily & fast

### Tasks:
- [x] Design Proposal
- [x] UI Discussion: how to group providers (type vs state, the use of labels...)? https://github.com/CartoDB/design/issues/1725
- [x] Upload / connect split https://github.com/CartoDB/cartodb/issues/15207
  - New dataImportView tab (WIP)
  - Remove dataImport from import options
- [x] Basic connectors listing https://github.com/CartoDB/cartodb/issues/15208
  - Remove tabs from ImportView
  - List Connectors
  - Switch view when selected
  - New header for provider with back option
- [x] Interest in Other provider: https://github.com/CartoDB/cartodb/issues/15199
- [x] Basic tests
- [x] Staging deployment for acceptance

### Acceptance
**Do** connect to staging (feature-branch)
**Then** try to add a new dataset in the web app
**Verify** You get many connector options, including your desired one (or a way to request it). For each one of the available ones you get clear instructions to use or enable.
