### ISSUE TITLE
[connectors-ui] New UI for connectors - UX improvements 

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15197]
To be implemented after https://github.com/CartoDB/cartodb/issues/15194

### Story
*As a* user
*I want* to have a POLISHED way to connect to many different data sources (more than the currently displayed)
*So that* I can work with my own data easily & fast

### Tasks:
- [ ] New header for provider
- [ ] Change errors style
- [ ] Fix rows in cloud providers (no choose button + periodicity included in row)
- [ ] Remove _Shared datasets_ tab
- [ ] Basic tests
- [ ] Doc per provider

### Acceptance
**Do** connect to staging (feature-branch)
**Then** try to add a new dataset in the web app
**Verify** You get many connector options, including your desired one (or a way to request it). For each one of the available ones you get clear instructions to use or enable.
**Verify 2** All team members and stakeholders are ok with it / Implementation matches [this invision](https://projects.invisionapp.com/share/QUULMAVESAW#/screens/390965264_Upload)
