### ISSUE TITLE
[BQ Connector] Improve UI & add new required inputs

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15284]
*As a* Builder user
*I want* to use the BQ connector in a nice UI, with the proper inputs
*So that* I can get my data into the Platform, and decide on which project to bill my SQL queries

### Tasks:
- [x] Prepare local dev env for BQ (& staging)
   - [x] new frontend proj
   - [x] OAuth config
   - [x] Install odbc in vagrant
- [x] Check new BQ conn fits new UI design + oauth (form)
- [x] Main form BQ
   - [x] Basic structure (no left panel)
   - [x] Add new required field: project billing
   - [x] Adapt sql >> text area
- [x] 'Beta' complements:
   - [x] Add Beta indicator on provider header
   - [x] Add link to (new?) GForm feedback form --> ask Pablo
   - [x] **Allow both Beta and 'Enabled/Disabled' dimensions** for any provider (BQ is the first example).    
- [x] Add BigQuery logo in Account settings page

### Acceptance
**Do** connect with a user with BQ connector enabled
**Then** try to connect to a Dataset, choosing BQ conn.
**Verify** oauth connection works (1st time) and after accepting, a proper form is presented and it works correctly
