### ISSUE TITLE
[PostgreSQL] Connection screen

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15396]
This is the screen where we gather the connection params and check them via Import API. We want it to be extensible to other Database connectors.

## Tasks
- [x] New `ImportDatabase` view as the main view that includes and manages others
- [x] New `ImportDatabaseConnectForm` view as the form view
  - [x] Markup: form and sidebar
  - [x] Check connection params calling Import API
  - [x] If params are ok go to next screen.
  ~- [ ] If params are not ok display an error message.~ (this will be done on another issue)

## Related info
- Design: https://invis.io/QUULMAVESAW#/390965275
