### ISSUE TITLE
[PostgreSQL] SQL query screen

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15415]
This is the screen where we get a SQL query and we import the resulting dataset into the Dashboard. We want it to be extensible to other Database connectors.

## Tasks
- [x] New `ImportDatabaseQueryForm` view as the form view
  - [x] Markup
  - [x] Get SQL query to import
- [x] New `ImportDatabaseSelectedDataset` view so the user can select the sync options
- [x] Import data

## Related info
- Design: https://invis.io/QUULMAVESAW#/390965275
