### ISSUE TITLE
Create delete dialog action

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1621]
- [x] [#1633 - Create the simplest delete dialog action](1633)
- [x] [#1675 - Show users that would be affected if datasets/maps are deleted](1675)
- [x] [#1687 Show maps that would be affected if datasets are deleted](1687)
- [x] [#1687 Show both users + maps that would be affected if datasets are deleted](1687)
- [x] Don't let delete datasets or maps where user is not the owner.
- ~~Add "Export data" link (in text) + button (in foot) to export dialog (awaits #1658)~~ [removed from scope for now](https://github.com/CartoDB/cartodb/issues/1660#issuecomment-69063315)
- ~~Display [processing dialog](https://github.com/CartoDB/cartodb/issues/1633#issuecomment-68736291) while deleting items~~ postponed to later sprint, see #1825

**Comment by xavijam** [comment]
Added a new subtask @viddo.

**Comment by viddo** [comment]
Updated description to remove comments that are not relevant anymore, and updated with references.
Closing the issue since all items for sprint are done :shipit:
