### ISSUE TITLE
New public dashboard

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#2034]
This issue outlines the analysed requirements and rationales for planning of implementing the public pages in the scope of the new dashboard.

#### Requirements
- Maintain current render approach:
  - Render static pages server-side
  - Minimise JS usage to interactive parts
  - Cache statically rendered pages (done by varnish)
- Styles/CSS
  - Look & feel according to new style guide and design mockups
  - Reuse same styles as implemented for (private) new dashboard
  - Modern browser support ("evergreen" browsers, IE10+)
  - Responsive (start from mobile and up)
- Control access by feature flag (based on viewed profile rather than current user)
- Reuse existing routes where makes sense

#### Scope & milestones
Feature will be implemented in small iterations:

- [x] Basic profile (issue #2007 / PR #2022)
- [x] Fav-map (issue #2043 / PR #2060)
- [x] Datasets (issue #2084 / PR #2088)
- [x] Pagination (issue #2157 / PR #2164)
- [x] Organization profile (issue #2179 / PR #2192)
- [x] Logged-in + Responsive design (issue #2200 / PR #2221)
- ~~Filters~~ postponed, since cannot be cached easily
- ~~Notifications~~, since don't have access to them there

**Comment by viddo** [comment]
@xavijam @saleiva @javisantana created this issue to track the overall scope for the new public dashboard, and how I plan to implement it.

Discussed the filters view (liked, order-by's) w/ @javisantana and @xavijam and we decided to leave that out for now, since there are issues related with caching that we can't tackle right now.

Let me know if I missed anything or if you have any other concerns

**Comment by xavijam** [comment]
For me, everything is :+1: . Small details should be discussed in each ticket.

**Comment by viddo** [comment]
I'll create new issues as I start implementing, but if you have some concerns start by bringing them up here, and I'll create issues earlier if necessary to keep discussions threaded.

**Comment by viddo** [comment]
finished with last PR, #2221
