### ISSUE TITLE
New dashboard UI fixes

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#2330]
- [x] `.Header-settingsItemAvatar` => `.Header-settingsItem--avatar` (https://github.com/CartoDB/cartodb/commit/054efd4e8fe78f4682c2d639e29ae3138484f438)

---

- [x] Underline shouldn't appear  in tags (https://github.com/CartoDB/cartodb/commit/657386a43859ee7ff2465168f7f535eaa7fa55c1)

![image](https://cloud.githubusercontent.com/assets/1214201/6265805/768f321a-b832-11e4-9e6c-8123e5a44a0c.png)

---

- [x] Weird vertical align in avatar (Duplicated)

![image](https://cloud.githubusercontent.com/assets/1214201/6265890/41dc4994-b833-11e4-94fa-bc0b66bd0fc9.png)

---

- [x] Deselect elements when press ESC (Moved -> https://github.com/CartoDB/cartodb/issues/2026)

---

- [x] 20 px margin (https://github.com/CartoDB/cartodb/commit/18441367ee46b513fe7a89163ebec7fb07076f4c)
![image](https://cloud.githubusercontent.com/assets/1214201/6265761/09d1a2c0-b832-11e4-9913-701b002857fe.png)

---

- [x] 20 px margin
![captura de pantalla 2015-02-19 12 03 55](https://cloud.githubusercontent.com/assets/1712650/6265514/92bb71f4-b82f-11e4-919c-50ce04950aed.png)

---

- [x] Underline shouldn't appear  in tags (Duplicated! https://github.com/CartoDB/cartodb/commit/657386a43859ee7ff2465168f7f535eaa7fa55c1)

![image](https://cloud.githubusercontent.com/assets/1214201/6265805/768f321a-b832-11e4-9e6c-8123e5a44a0c.png)

and here

![image](https://cloud.githubusercontent.com/assets/1214201/6268142/d3082958-b84a-11e4-97c7-011cfa8000b1.png)

---

- [x] Deselect elements when press ESC (Duplicated and moved -> #2026)

---

- [x] Gradient? (Duplicated! https://github.com/CartoDB/cartodb/commit/1b093d03f136fd2ee1840334d0fa8745bb0c4641)

![image](https://cloud.githubusercontent.com/assets/1214201/6266189/c89a7066-b836-11e4-861b-3f413ea26616.png)

---

- [x] Unify hovers? (https://github.com/CartoDB/cartodb/commit/657386a43859ee7ff2465168f7f535eaa7fa55c1)

![image](https://cloud.githubusercontent.com/assets/1214201/6266279/b82a7766-b837-11e4-9e67-921ec36aabc7.png)

---

- [x] change position "Show your..." (Not for the moment, it requires change several things)

![image](https://cloud.githubusercontent.com/assets/1214201/6267478/bd153786-b844-11e4-8594-35b3204938b9.png)

"There are not locked..." is this proper english? "There are no locked.." or "There aren't any locked..."

---

- [x] Unify progressbar (https://github.com/CartoDB/cartodb/commit/1b093d03f136fd2ee1840334d0fa8745bb0c4641)

![image](https://cloud.githubusercontent.com/assets/1214201/6267592/98c24c06-b845-11e4-9092-e5a43994126f.png)

---

- [x] Equal space between icons (https://github.com/CartoDB/cartodb/commit/054efd4e8fe78f4682c2d639e29ae3138484f438)

![image](https://cloud.githubusercontent.com/assets/1214201/6267927/b0559668-b848-11e4-9444-8d5352640f28.png)

---

- [x] Sync icon not aligned on retina (already fixed in production)

![screen shot 2015-02-19 at 15 16 12](https://cloud.githubusercontent.com/assets/36676/6268103/57a0e16a-b84a-11e4-8a10-18be0e6e5f54.png)

---

- [x] Add more space between "Start..." and line (https://github.com/CartoDB/cartodb/commit/a4c53c1dd473671d1b6aca365e43c86edd1e0872)

![image](https://cloud.githubusercontent.com/assets/1214201/6268986/d396da3a-b850-11e4-8eed-bae25a95f725.png)

---

- [x] Blurry line between Search and Tabs (https://github.com/CartoDB/cartodb/commit/04ed5be430ef9a700963ed8e88fd6cf077a3d93f)

![image](https://cloud.githubusercontent.com/assets/1214201/6269106/79821be4-b851-11e4-989e-d9ca24a89428.png)

---

- [x] Remove (i) icon from these annotations (https://github.com/CartoDB/cartodb/commit/3d5867faa802c23c503608208af592247c5ce0c8)

![screen shot 2015-02-19 at 16 13 33](https://cloud.githubusercontent.com/assets/132149/6269278/6316577a-b852-11e4-8d9c-1debbb476d6e.png)

---

- [x] Weird align  (As it is in the design)

![image](https://cloud.githubusercontent.com/assets/1214201/6269341/d5addc22-b852-11e4-8a65-454d2651208d.png)

---

- [x]  Fix align when the dataset has description (https://github.com/CartoDB/cartodb/commit/9c8b31d4e0f20f7d37872b54e79377ae5716dbbb)

![image](https://cloud.githubusercontent.com/assets/1214201/6269627/b667a2ba-b854-11e4-945b-8254d09b5ef0.png)

---

- [x] if you don't have locked datasets, I didn't find where were they, a "There are not locked maps" literal in the previous place (or in the place "Show your 5 non-locked maps" literal appear once in locked) would be appreciated -> We have to make a request to know if there is or isn't locked maps or datasets, so for the moment that way is the normal one :S.

---

- [x]  Unify hover in white buttons (https://github.com/CartoDB/cartodb/commit/0174f81968f56a0fd3b1b86b69a9d6e9247ad41c)

![image](https://cloud.githubusercontent.com/assets/1214201/6272636/7325e394-b869-11e4-8207-5929e54c9815.png).

This also happening here. We should keep the option than just makes the border darker

![screen shot 2015-02-20 at 12 48 17](https://cloud.githubusercontent.com/assets/132149/6285697/ece5450e-b8fe-11e4-915b-b1997335b42e.png)

---
- [x] fix paddings (https://github.com/CartoDB/cartodb/commit/b92f0ac544c0c436cc7befd62e757b24d21ef715)

![image](https://cloud.githubusercontent.com/assets/1214201/6267627/f3ad91f2-b845-11e4-9d1f-4af5e89901eb.png)

---
- [x] Unify placeholders style on inputs. (https://github.com/CartoDB/cartodb/commit/15e670f461f1b31960e3d2af3dae40564d433f1a)
 They should be light and soft and italic

---
- [x] colors/contrasts -> This is for designers (https://github.com/CartoDB/cartodb/issues/2441)

Some colors are almost not visible on an external screen (with normal calibration settings), in particular:
  - selected datasets/maps item/card
  - the grey background (e.g. applied in the footer)

---

- [x] Gradient for scroll panels missing. It should have a gradient from grey to transparent that indicates that there are more stuff if you scroll. (https://github.com/CartoDB/cartodb/commit/93ed4da3070b7124f1e5e605242868a242be4cfe)

![screen shot 2015-02-19 at 15 07 52](https://cloud.githubusercontent.com/assets/132149/6267994/328aab32-b849-11e4-9dcb-c55418de3bd2.png)

---
- [x] Weird align ((https://github.com/CartoDB/cartodb/commit/e185a4d732640d441eaafb31da0cfcbbe28b910f))

![image](https://cloud.githubusercontent.com/assets/1214201/6268334/2d56d016-b84c-11e4-9a64-1b396623d24b.png)
---

- [x] Fix Vertical alignment on remove search applied terms on the create map modal (https://github.com/CartoDB/cartodb/commit/6739c6f53ed84ca1f735efa70d2190dcaec984af)

![screen shot 2015-02-19 at 16 16 50](https://cloud.githubusercontent.com/assets/132149/6269344/daa2ee8e-b852-11e4-80ad-013c41703723.png)

---

- [x] Weird vertical align in avatar (https://github.com/CartoDB/cartodb/commit/c27499b6a30f163d67339280a13d8a5b54846ca3)

![image](https://cloud.githubusercontent.com/assets/1214201/6265890/41dc4994-b833-11e4-94fa-bc0b66bd0fc9.png)
---

- [x] Blurry icons (Created ticket for this task, designers come to me! https://github.com/CartoDB/cartodb/issues/2453)

![image](https://cloud.githubusercontent.com/assets/1214201/6266007/8cf1007c-b834-11e4-8250-1df4f9359d98.png)
![image](https://cloud.githubusercontent.com/assets/1214201/6266159/504e6720-b836-11e4-9040-8857dce44089.png)
![image](https://cloud.githubusercontent.com/assets/1214201/6266828/859a95fe-b83e-11e4-9bae-ae7e0f99f07e.png)

---

- [x] Fix Vertical align (https://github.com/CartoDB/cartodb/commit/2e8f0cccc407dd18216dde7c49abd91df9c447b7)

![image](https://cloud.githubusercontent.com/assets/1214201/6268869/08912df4-b850-11e4-81dc-80558f838344.png)

---

- [x]  Fix weird align, in Search component when you want connect dataset (https://github.com/CartoDB/cartodb/commit/d92e7f845a699e441fb4b2f326707a2a76209f86)

![image](https://cloud.githubusercontent.com/assets/1214201/6284805/d1e9f25e-b8f4-11e4-8f4d-b50c2b664f51.png)

**Comment by carlostallon** [comment]
- [ ] 20 px margin
![captura de pantalla 2015-02-19 12 03 55](https://cloud.githubusercontent.com/assets/1712650/6265514/92bb71f4-b82f-11e4-919c-50ce04950aed.png)

**Comment by xavijam** [comment]
It should be done! :D :dancer: -> https://github.com/CartoDB/cartodb/pull/2444
