### ISSUE TITLE
Analyze slow imports

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3835]
## Tasks

- [x] Create sequence and use it instead of boolean field to improve query planning
- [x] Replace all old QueryBatcher calls by new system
- [x] Rename `CartodbIdQueryBatcher` to `IdBasedQueryBatcher`
- [x] Build tests for the new code
- [x] Research Mailchimp datasource improvements

## Data samples:

(1)
- https://data.cityofchicago.org/Community-Economic-Development/Business-Licenses-Current-Active/uupf-x98q

- https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5
121MB exported as CSV

(2)
- https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Vacant-and-Abandoned-Building/7nii-7srd
- https://data.cityofchicago.org/Transportation/Average-Daily-Traffic-Counts/pfsx-4n4m

(3)
- https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Vacant-and-Abandoned-Building/7nii-7srd
- https://data.cityofchicago.org/Public-Safety/Crimes-2014/qnmj-8ku6

(4)
- Mailchimp

<del>Branch: `3835-new-query-batcher`</del>
Branch for mailchimp improvements: `optimize-mailchimp-connector`

**Comment by Kartones** [comment]
- Timing using `.../rows.csv?accessType=DOWNLOAD`, so our worker directly downloads the file instead of me + upload.
- **Import logs**: Times are first log entry and last log entry timestamps
- **Chrome HARs**: timing in ms since  `POST to api/v1/imports` with data until the `GET to /api/v1/viz/` that lists the new table after import

1.1) `https://data.cityofchicago.org/api/views/uupf-x98q/rows.csv?accessType=DOWNLOAD`
Import log: `[2015-05-29 09:03:09, 2015-05-29 09:03:50] = 41 sec`
Chrome HAR: `[41354, 99251] = 57897 ms`

**Comment by Kartones** [comment]
1.2) `https://data.cityofchicago.org/api/views/4ijn-s7e5/rows.csv?accessType=DOWNLOAD`
121MB exported as CSV
**In live still importing**

Local import (inside a VM'ed Linux): `[2015-05-29 10:09:10 UTC, 2015-05-29 10:13:07 UTC] = 4 minutes`
Processing of blocks (what's taking a lot in live) in local:
```
2015-05-29 10:12:20 UTC: Populating the_geom from latitude / longitude
2015-05-29 10:12:23 UTC: Total processed: 19941
2015-05-29 10:12:26 UTC: Total processed: 39812
2015-05-29 10:12:29 UTC: Total processed: 59624
2015-05-29 10:12:32 UTC: Total processed: 79362
2015-05-29 10:12:36 UTC: Total processed: 99019
2015-05-29 10:12:40 UTC: Total processed: 103735
2015-05-29 10:12:43 UTC: Total processed: 103735
```
vs processing of blocks in live:
```
2015-05-29 09:17:07 UTC: Populating the_geom from latitude / longitude
2015-05-29 09:41:11 UTC: Total processed: 19941
2015-05-29 10:05:49 UTC: Total processed: 39812
```

**Comment by Kartones** [comment]
With the invaluable help of @zenitraM we've found the following:

When the import takes a lot, it uses a temporal file to read it and sort:
`postgres 21876 postgres   17u   REG            202,224  96876962 2153373710 /mnt/pg_data/base/pgsql_tmp/pgsql_tmp21876.3` 
which takes ages to process each 20k batch rows.

With a small LIMIT 20, the lat/lon georeferncing function gets planned like:
```
 Update on importer_7f4437c405ef11e582be0e6e1df11cbf  (cost=0.08..73943.40 rows=1 width=484)
   ->  Nested Loop Semi Join  (cost=0.08..73943.40 rows=1 width=484)
         Join Filter: (importer_7f4437c405ef11e582be0e6e1df11cbf.ctid = "ANY_subquery".ctid)
         ->  Seq Scan on importer_7f4437c405ef11e582be0e6e1df11cbf  (cost=0.00..73820.17 rows=554 width=454)
               Filter: ((replace(btrim((longitude)::text), ','::text, '.'::text) ~ '^(([-+]?(([0-9]|[1-9][0-9]|1[0-7][0-9])(.[0-9]+)?))|[-+]?180)$'::text) AND (replace(btrim((latitude)::text), ','::text, '.'::text) ~ '^(([-+]?(([0-9]|[1-8][0-9])(.[0-9]+)?))|[-+]?90)$'::text))
         ->  Materialize  (cost=0.08..78.92 rows=20 width=36)
               ->  Subquery Scan on "ANY_subquery"  (cost=0.08..78.90 rows=20 width=36)
                     ->  Limit  (cost=0.08..78.84 rows=20 width=6)
                           ->  Index Scan using idx_cartodb_processed_2724892225813558037 on importer_7f4437c405ef11e582be0e6e1df11cbf importer_7f4437c405ef11e582be0e6e1df11cbf_1  (cost=0.08..11297.00 rows=2869 width=6)
                                 Index Cond: (cartodb_processed_2724892225813558037 IS NULL)
(10 rows)```
```

With a big enough LIMIT (like 1k), the query planner changes how it fetches data:
```
 Update on importer_7f4437c405ef11e582be0e6e1df11cbf  (cost=3387.34..77651.99 rows=277 width=484)
   ->  Nested Loop  (cost=3387.34..77651.99 rows=277 width=484)
         Join Filter: (importer_7f4437c405ef11e582be0e6e1df11cbf.ctid = "ANY_subquery".ctid)
         ->  Unique  (cost=3387.34..3388.34 rows=200 width=36)
               ->  Sort  (cost=3387.34..3387.84 rows=1000 width=36)
                     Sort Key: "ANY_subquery".ctid
                     ->  Subquery Scan on "ANY_subquery"  (cost=44.53..3377.38 rows=1000 width=36)
                           ->  Limit  (cost=44.53..3374.38 rows=1000 width=6)
                                 ->  Bitmap Heap Scan on importer_7f4437c405ef11e582be0e6e1df11cbf importer_7f4437c405ef11e582be0e6e1df11cbf_1  (cost=44.53..9597.86 rows=2869 width=6)
                                       Recheck Cond: (cartodb_processed_2724892225813558037 IS NULL)
                                       ->  Bitmap Index Scan on idx_cartodb_processed_2724892225813558037  (cost=0.00..44.39 rows=2869 width=0)
                                             Index Cond: (cartodb_processed_2724892225813558037 IS NULL)
         ->  Materialize  (cost=0.00..73820.72 rows=554 width=454)
               ->  Seq Scan on importer_7f4437c405ef11e582be0e6e1df11cbf  (cost=0.00..73820.17 rows=554 width=454)
                     Filter: ((replace(btrim((longitude)::text), ','::text, '.'::text) ~ '^(([-+]?(([0-9]|[1-9][0-9]|1[0-7][0-9])(.[0-9]+)?))|[-+]?180)$'::text) AND (replace(btrim((latitude)::text), ','::text, '.'::text) ~ '^(([-+]?(([0-9]|[1-8][0-9])(.[0-9]+)?))|[-+]?90)$'::text))
(15 rows)
```

**Comment by Kartones** [comment]
ok, after talking with @pramsey , at least for found bottleneck at points 1) to 3) and general improvement of the import process, I'll modify the query batcher in two steps to:
1) add a sequence field (and index it instead of the processed field), to batch using both that and processed = false filter. This will get rid of degrading query planner performance on big tables due to having "processed" being constantly updated and used to filter.
2) Get rid of the processed field to save ALTERs, UPDATEs, etc. and make Query batcher "smarter" by checking for existance of cartodb_id and if presente use it instead of creating a new one.

For point 4) will check afterwards, as that might have some specific issues gathering the data (before the import itself takes place).

**Comment by iriberri** [comment]
Same file: csv.csv

````
one, two
a, a
````

user: iriberri
database: dbd13
import id: 70ba6e6f-7cbd-43e4-94db-c275f1279c6c
started at: 2015-06-01 10:41:15 
finished at: 2015-06-01 10:50:17

====

user: crb
database: dbd11
import id: 65dd07f1-782f-40b4-b7be-83b5386025ee
started at: 2015-06-01 12:22:35
finished at: 2015-06-01 12:24:07

====

user: vmg
database_host: dbd13
import id: 8b25e40b-da67-4e64-a5fb-4d6b58a172fe
started at: 2015-06-01 12:23:08
finished at: 2015-06-01 12:23:17

**Comment by rafatower** [comment]
Part of the problem seems to be ogr2ogr performing heavy queries on system tables:
```
2015-06-01 13:03:34 UTC LOG:  execute <unnamed>: DECLARE mycursor CURSOR for SELECT c.relname, n.nspname, c.relkind, g.f_geometry_column, g.type, g.coord_dimension, g.srid, 1, a.attnotnull, c.oid as oid, a.attnum as attnum FROM pg_class c,
 pg_namespace n, geometry_columns g, pg_attribute a WHERE (c.relkind in ('r','v') AND c.relname !~ '^pg_' AND c.relnamespace=n.oid AND c.relname::TEXT = g.f_table_name::TEXT AND n.nspname = g.f_table_schema AND a.attname = g.f_geometry_col
umn AND a.attrelid = c.oid) UNION SELECT c.relname, n.nspname, c.relkind, g.f_geography_column, g.type, g.coord_dimension, g.srid, 2, a.attnotnull, c.oid as oid, a.attnum as attnum FROM pg_class c, pg_namespace n, geography_columns g, pg_a
ttribute a WHERE (c.relkind in ('r','v') AND c.relname !~ '^pg_' AND c.relnamespace=n.oid AND c.relname::TEXT = g.f_table_name::TEXT AND n.nspname = g.f_table_schema AND a.attname = g.f_geography_column AND a.attrelid = c.oid) ORDER BY oid
, attnum
```
https://github.com/CartoDB/gdal/blob/ogr2ogr2/gdal/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp#L839-L843

Apparently solved in gdal trunk.

**Comment by Kartones** [comment]
Related with point 4) I left a staging server with new QueryBatcher code importing and it took around 21 minutes in the "Upload" phase, that is, importing data from Mailchimp, plus around 1 minute to do all post-processing.

I'll try one improvement regarding mailchimp and see how it goes.

**Comment by Kartones** [comment]
`list_json_to_csv` inside Mailchimp connector seems to eat most of the import time doing some timings, so working on improving it.

**Comment by juanignaciosl** [comment]
Do we have duration comparison of cartodb_id-based batcher against the new one with a big enough file?

**Comment by Kartones** [comment]
@juanignaciosl no because @saleiva was in such a hurry that I directly implemented new version and pushed it.

**Comment by Kartones** [comment]
@rafatower ogr2ogr stuff is then fixed now? because I also have point 4) so we could close this ticket tomorrow

**Comment by rafatower** [comment]
@Kartones ogr2ogr stuff is fixed

**Comment by Kartones** [comment]
Bravo! :D

**Comment by Kartones** [comment]
Closing this task as with #3897 we close all related tasks
