### ISSUE TITLE
create a named map for every single visualization

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3879]
Details by @kartones:

## Tasks

- [x] Store named maps for all types of vis, public or private [#3918](https://github.com/CartoDB/cartodb/pull/3918)
- [x] Migrate existing vis so all have named maps <del>[#3918](https://github.com/CartoDB/cartodb/pull/3918)</del> [#3954](https://github.com/CartoDB/cartodb/pull/3954) (needs release of branch `3879-improved-script` and run `cartodb:vizs:create_named_maps` rake). **<- Last 11k failed (out of 374k)**
- [x] Remove checks of "has named map" etc. and simplify code
- Add new fields required for static maps:
- [x] Add to named map basemap layer ('http') ([doc](https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/Map-API.md#arguments))
- [x] Add bounding box to named map ("view" layer, [doc](https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/Map-API.md#named-map)).
- [x] Tests for newly added fields
- [x] Migrate to add values for existing named maps (no need for new script, just re-running existing one)
- [x] <del>Relax naming restraints of templates (see [Windshaft part](https://github.com/CartoDB/Windshaft-cartodb/issues/306))</del>
- [x] <del>Migrate existing template names? duplicate them? (needs planning after previous point is done)</del>
<hr>

## Branches
- <del>`3879-named-maps-everywhere`</del>
- <del>`3879-improved-script`</del>
- <del>`3879-clean-named-maps-checks`</del>
- `3879-new-named-maps-fields` ([PR](https://github.com/CartoDB/cartodb/pull/3998), needs reverting)

## Description (original by @javisantana )

so we can generate previews for all the visualizations:

``http://...../named/e1986900-cd40-11e4-b81f-0e43f3deba5a/width/height.png``

this also needs a task to update all the current maps so:

- include the basemap
- include the map view bounds information

@rochoa will point here to the documentation

**Comment by rochoa** [comment]
Some examples about what we need/want can be found in the official documentation: http://docs.cartodb.com/cartodb-platform/maps-api.html#examples

Names for the named maps / templates right now are limited to: `Valid names start with a letter, and only contain letters, numbers, or underscores (_).` http://docs.cartodb.com/cartodb-platform/maps-api.html#arguments
Probably we want to change that so we don't have to do any workaround like `name = 'tpl_' viz.id.replace('-', '_')` as we do now., don't we?

**Comment by javisantana** [comment]
\o/

**Comment by rochoa** [comment]
:heart:
