### ISSUE TITLE
[META] 5k-orgs login and signup

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4122]
- [X] Organization user login #4026.
- [X] Error deleting org because of undefined method `acl' for nil:NilClass #4092.
- [ ] ~~Massive user creation issues #3859: pending QA.~~ Moved to next milestone.
- [ ] ~~Organization user signup #3902: pending QA.~~ Moved to next milestone.
- [X] New organization configuration parameters #4036
- [X] Organization user login is not showing the organization login layout #4074.
- [X] Design the loading, success and error steps after a new signup within an organization #4090.
