### ISSUE TITLE
Geocode fixes

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4262]
So after test geocode I found a few little things:

- [x] `#666` header icons color and change header copy to `Transform your data into coordinates`: _fixed in #4370_
![screen shot 2015-07-07 at 7 04 53 pm](https://cloud.githubusercontent.com/assets/596509/8552093/155680e6-24db-11e5-979b-db136cbceecb.png)

- [x] Update points icon from: _fixed in #4372_
![screen shot 2015-07-08 at 11 57 28 am](https://cloud.githubusercontent.com/assets/596509/8567921/8361c706-2569-11e5-8c6e-f5344ef793bd.png)
to this:
![screen shot 2015-07-08 at 12 05 07 pm](https://cloud.githubusercontent.com/assets/596509/8567931/9f1cc69e-2569-11e5-87f8-ecf2732bee47.png)

- [x] Delete Learn more and its tooltip: _fixed in #4372_
![screen shot 2015-07-08 at 11 16 46 am](https://cloud.githubusercontent.com/assets/596509/8567970/150e7c58-256a-11e5-9ae6-89c4c52bde4a.png)

- [x] To unify this type of boxes, we decided to make them one-click, just like Merge tables one behaves. So no confirm button needed.
  -  _fixed in #4372_

- [x] Subheader to go back: _fixed in #4380_
![screen shot 2015-07-02 at 11 40 20 am](https://cloud.githubusercontent.com/assets/596509/8474262/2a3532e4-20af-11e5-8bfa-1c8856dbfb10.png)

- [x]  Fix header tabs distance: _fixed in #4380_
(they are 20px and should be 30px)
![screen shot 2015-07-07 at 5 34 04 pm](https://cloud.githubusercontent.com/assets/596509/8550106/d25abf7a-24ce-11e5-9673-24c10d8dac29.png)

- [x] As @xavijam mentioned on #4255 here are some enhancements to the dropdown (the "arrow" should be the same):
![screen shot 2015-07-02 at 12 11 32 pm](https://cloud.githubusercontent.com/assets/596509/8474859/b1f4800a-20b3-11e5-8546-b8098f469789.png)

- [x] Header text to options space should be 40px:
This:
![screen shot 2015-07-07 at 6 55 15 pm](https://cloud.githubusercontent.com/assets/596509/8551890/c5d996f8-24d9-11e5-9313-2184a351d39b.png)
instead of this:
![artboard](https://cloud.githubusercontent.com/assets/596509/8551861/89f4e3b8-24d9-11e5-951d-9d1d9e097d5f.png)

 - [x] Spacings between options should be 28px:
![screen shot 2015-07-08 at 12 32 49 pm](https://cloud.githubusercontent.com/assets/596509/8568428/d24575bc-256d-11e5-9587-96cf7f284a2b.png)
![screen shot 2015-07-08 at 12 35 51 pm](https://cloud.githubusercontent.com/assets/596509/8568439/eac4762e-256d-11e5-852e-e95095b6b7fa.png)

- [x] Green icon when you select a column:
![screen shot 2015-07-02 at 11 40 59 am](https://cloud.githubusercontent.com/assets/596509/8474281/4ab5378a-20af-11e5-8fc0-cb24f2fbb150.png)

- [x] Thanks to @iriberri for spotting this) On small windows, footer's button does not show.
![screen shot 2015-07-07 at 6 59 31 pm](https://cloud.githubusercontent.com/assets/596509/8551975/53975070-24da-11e5-82b9-15416ef53345.png)

**Comment by josecruz** [comment]
@viddo Updated list! (you're going to hate me more after this :disappointed: )

**Comment by viddo** [comment]
No hate over here, thx for updating ;)
