### ISSUE TITLE
Pecan fixes

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4299]
### Pending
- [x] Add heatmap.
- [ ] Review SQL cache
- [ ] Cache the analysis
- [ ] Histogram on choropleth cards (https://github.com/CartoDB/cartodb.js/issues/567)
- [x] Implement a better skip system (https://github.com/CartoDB/cartodb/issues/4296)
- [ ] Mark layer as "analysed by pecan".

### Future
- [ ] Design a way to reopen the pecan dialog from the map editor (#4305)
- [ ] Do simple torque analysis.

### Done
- [x] Update boolean colors
- [x] SQL problems: https://github.com/CartoDB/cartodb/issues/4479
- [x] Fix a problem generating static previews from private datasets.
- [x] Apply the decision tree to accept/reject columns.
- [x] Enable choropleth ramps for L, J, A, U, S, F shapes.
- [x] Apply heterogeneity test (at least 80% in the first 10 categories) (`skew`).
- [x] Fixes an issue selecting the wrong column.
- [x] Apply right quantification method depending on the data distribution.
- [x] Limit analysis by column number.
- [x] Guess maps when all columns have been analysed (#4307)
- [x] Enable analysis for date columns (https://github.com/CartoDB/cartodb.js/pull/559)
- [x] Center the cards when having less than 3.
- [x] Show torque cards the first ones.
- [x] Fix color difference between static preview / actual map (current issue has to do with the firing of wizard_properties events, so there are some sporadic problems)
- [x] null_count and null_ratio are not having the empty strings into account  (https://github.com/CartoDB/cartodb.js/issues/563)
- [x] Add specs. 
- [x] Apply the head/tails quantification method based on the distinctPercentage  (> 75%, float and L or U shapes)
- [x] Enable analysis for boolean columns (https://github.com/CartoDB/cartodb.js/issues/568)
- [x] Bubble maps instead of choropleth maps when having point datasets. (https://github.com/CartoDB/cartodb.js/issues/582)
- [x] New conditions on decission tree (https://github.com/CartoDB/cartodb/issues/4387)
- [x] Stoping Pecan should stop the requests (https://github.com/CartoDB/cartodb/issues/4376)
- [x] Truncate the null_count
- [x] Async analysis for different cards (https://github.com/CartoDB/cartodb/issues/4369)
- [x] Add pecan to the background importer. 
- [x] Show in any way that torque maps will be animated.
- [x] Review color ramp criteria.

**Comment by saleiva** [comment]
cc @xavijam 
![screen shot 2015-07-15 at 18 23 44](https://cloud.githubusercontent.com/assets/132149/8703667/c60ea4ba-2b1e-11e5-835a-2e75596e98b8.png)

**Comment by xavijam** [comment]
:+1:

**Comment by javierarce** [comment]
I'm closing this and opening tickets for the pending issues (in case they didn't have them)
