### ISSUE TITLE
New modals fixes

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4579]
## Privacy modal
- [x] In this modal, all green buttons should be blue `#0090d7`.

- [x] Header margins + header icon `#666`:
                        There are wrong margins here. First, icon to text should be 12px (as in connect dataset)
![screen shot 2015-07-20 at 3 42 28 pm](https://cloud.githubusercontent.com/assets/596509/8779709/ecd116d4-2f04-11e5-87e2-e694044c31fc.png)
![screen shot 2015-07-20 at 3 42 43 pm](https://cloud.githubusercontent.com/assets/596509/8779720/fb7953e0-2f04-11e5-9600-77c1cdbc0fd0.png)
- [x] Also, we're going to remove the footer tip and align cancel button to the left.

- [x] Font should be Lato and the text color should match the rest of the modals
![screen shot 2015-07-20 at 5 03 35 pm](https://cloud.githubusercontent.com/assets/596509/8780893/48205e76-2f0c-11e5-8119-6c2cb954691c.png)

- [x] Header size should be the same as connect dataset one:
![screen shot 2015-07-20 at 3 41 45 pm](https://cloud.githubusercontent.com/assets/596509/8779751/3c09b47c-2f05-11e5-956a-2d48dd2119ec.png)

## Delete modal
- [x] Line width is not the same:
![artboard](https://cloud.githubusercontent.com/assets/596509/8779922/303d882a-2f06-11e5-9a9d-a7ff48c4e7a4.png)

## Lock/Unlock dataset
- [x] Unlock button should be blue `#0090d7`
![screen shot 2015-07-20 at 4 07 41 pm](https://cloud.githubusercontent.com/assets/596509/8780318/831649c2-2f08-11e5-8931-38b98ff88faa.png)

## Add custom basemap
- [x] Header icon should be `#666`
![screen shot 2015-07-20 at 6 16 58 pm](https://cloud.githubusercontent.com/assets/596509/8780800/a1b819c0-2f0b-11e5-82d0-b3d34f10a358.png)

- [x] All footer buttons should be blue `#0090d7`
![screen shot 2015-07-20 at 6 31 16 pm](https://cloud.githubusercontent.com/assets/596509/8781148/af1cad2c-2f0d-11e5-8560-ce9446230f7a.png)

- [x] Deactivate Add Basemap button on Mapbox tab:
                        We actually deactivate all buttons when there's an empty form on all tabs but the Mapbox one
![addcustombasemap](https://cloud.githubusercontent.com/assets/596509/8798463/be30c75e-2fa2-11e5-9130-7cb3e94f2aef.gif)

## Marker image selector

- [x] Set image button should be blue `#0090d7`

- [x] Scroll on icon selector cuts the image:
![marker image](https://cloud.githubusercontent.com/assets/596509/8798907/070757ce-2fa6-11e5-840f-9cde9826bfb2.gif)

## Sync Dataset
- [x] Save settings button should be blue `#0090d7`.

## Edit Metadata
- [x] Header and header icon properties should be the same as in `Connect Dataset` modal
![screen shot 2015-07-21 at 1 23 18 pm](https://cloud.githubusercontent.com/assets/596509/8799632/b87592dc-2fab-11e5-9d33-4c11b887580d.png)

## Connect dataset
- [x] Footer tip needs the same margins as the rest of footer elements:
![screen shot 2015-07-21 at 2 33 58 pm](https://cloud.githubusercontent.com/assets/596509/8800804/0a15bd6a-2fb6-11e5-880d-bcb2cf7117a6.png)
