### ISSUE TITLE
Groups management UI

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4883]
edit: (@viddo) split up this epic issue to smaller ones, to be able to implement this in incremental steps. Also ordered them in terms of necessarily (must-have and nice-to-have buckets) to prioritise and implement them in natural order of usage.

This issue will serve as a "parent" issue to keep track on overall progress (will create issues as starting to work/discuss details per use-case):

**"Must-haves"**
- Organisation owner can:
  - [x] create a new group #5277
  - [x] see groups belonging to organization #5277
  - [x] edit group name #5277
  - [x] delete group #5277
  - [x] group details header navigation (users | settings) #5311
  - [x] add users to a group #5431
  - [x] browse add-org-users list through pagination #5431
  - [x] search add-org-users #5431
  - [x] apply visual styles #5431
  - [x] remove users from a group #5431
- Any user can:
  - [x] [Share dataset with a group #4851](https://github.com/CartoDB/cartodb/issues/4851)

**"Nice-to-have"**
- Organisation owner can:
  - [x] see datasets/maps count for each group #5629
  - [x] see count/avatar previews of group members #5629
  - [x] see datasets/maps count for each group user #5629
  - [x] browse/search groups #5781 
  - [x] browse/search groups users #5913 
  - [x] add users to a new group (w/o members) directly from group view #5923
  - [x] Show empty-message when there are no groups #5650 

---

Relevant references:
- [(Invision) UI proposal](https://projects.invisionapp.com/share/P43R5D79K#/screens/93104597)

cc @saleiva

**Comment by juanignaciosl** [comment]
@MariaCheca Don't do anything related to groups as part of redesign (#4880, #4878)

**Comment by juanignaciosl** [comment]
@viddo the branch I'm adding editor endpoints at is 5159-Group_resource_editor_API.

**Comment by juanignaciosl** [comment]
@saleiva @viddo Because of database restrictions we have two names: `name` and `display_name`. `display_name` is the only name a user will care about, and `name` will be a transformation of that name, which must be a valid postgresql identifier and will be the one used when editor has to talk to the extension. Just FYI, since I think we can hide this from the UI.

**Comment by viddo** [comment]
@juanignaciosl do you plan to merge that branch back to 4924-Group_metadata_API_endpoints when you're done?

re: the name, wouldn't it be better to flip that? I.e. use `name` as the canonical param (for the user as you mentions), and `table_name` (or `db_name_id` or whatever), since that's more of a detail between "editor"<->extension? do we need to expose that outside the API endpoint?

**Comment by juanignaciosl** [comment]
Yes, my plan is branching 4924 and merge them back when it's done, and merge 4924 to master when there're enough features for a release. But I don't think I'll finish all before you begin, so maybe we both can work in 5159 until it's complete.

¿What's your proposal for naming? `name` for the name displayed on screen, and `group_name` for the name used by the extension? I'm open to refactors on this, but I can't see a clear winner.

**Comment by viddo** [comment]
Trying to clarify my proposal/rationale for naming:

> Because of database restrictions we have two names: name and display_name. display_name is the only name a user will care about, 

I interpret this as the name that we'll use to render the group name in the UI would be what you refer to as `display_name`? And that the other one is requires to have a alphanumeric-kind-of value, required to communicate with the extension? That's why I proposed to "flip" (the names), so we used `name` for the UI, and some other name for the internals (extension etc.) instead. Because I find it more intuitive to just plain names for UI endpoints and keep restrictions closer to the source.

**Comment by viddo** [comment]
@juanignaciosl @saleiva updated the desc of this issue, after doing some preliminary planning. 

The must-haves will be done in [Malpica](https://github.com/CartoDB/cartodb/milestones/Malpica), but considering I will only be able to work half milestone and taking into account unplanned stuff I flag for that the other stuff might need to be accounted for the following milestone, we'll need to re-evalute once I start to implementing this and know better. 

Also asked about some specific doubts regarding the UI on the shared invision doc.

**Comment by viddo** [comment]
Updated scope after today's offline talk, to close this issue. 
UI for individual organization users is postponed for now, see #5895

**Comment by juanignaciosl** [comment]
Updated [groups schedule page](https://github.com/CartoDB/cartodb-management/wiki/Groups) so it can be looked up later, nice to have for this sprint and individual organization users for "Future".
