### ISSUE TITLE
User-Mover integration backend tasks

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#5922]
### Tasks

- [x] Fully namespace `User` model (`::User`) to avoid collisions with subclasses
- [x] Implement a common `configure_database` method (currently at `User::DBService`) so that both `UserMover` and user creation process share the same code
- [x] Manual tests: Normal user creation & login, org owner -> org member user creation & login, org member signup creation
- [x] add new tests: normal user (done), user mover (done)
- [x] Stabilize tests:
  - `spec/models/organnization_spec.rb` -> 'Destroys users and owner as well'
  - `spec/models/organnization_spec.rb` -> 'Tests removing a normal member from the organization'
- [x] Move all purely DB-related methods to subclasses (`User::DBService` and `User::DBQueries` subclasses, naming subject to change) **<- critical paths already done**, working the rest at `user-mover-user-model-splitting`

### Branch
`user-mover` (main)
`user-mover-user-model-splitting` (child, contains more `User` model splitting)
