### ISSUE TITLE
Setup view+markup for widgets content/list

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6455]
Scope:
- add data model representing a widget, and collection to hold them
- render widgets existing in vizJSON from start
- use new public API to add/remove widgets, ~~awaits~~ see https://github.com/CartoDB/deep-
insights.js/issues/90
- should be able to create/update/remove widgets from dev console

---

TODOs
- [x] create model + collection (from prior branch [`issue-6455`, master...a0c7bad](https://github.com/CartoDB/cartodb/compare/master...a0c7bad)
- [x] expose collection on `window`
- [x] create editor widget model and associate with DI widget (using new API)
- [x] define URL creation using Backbone's mechanism collection-model to be able to interact with API
- [x] organize data models and rename'em
- [x] :fire: [hardcoded map ID](https://github.com/CartoDB/cartodb/commit/a08b86d67692e744cd71739a10b41b669573895b#diff-d27b00749653f54e193fd10402d14d8dR58), awaits https://github.com/CartoDB/cartodb/issues/6499
- [x] update layerId to be layer_id, awaits #6497
- [x] render widget definitions (already created and existing in vizJSON)
- [x] :fire: `widgetDefinitionModel.parse`, awaits #6506 is fixed
- [x] create widget model when widget definition is saved
- [x] update DI dependency to use HEAD of master as commit-isch instead of WIP branch for https://github.com/CartoDB/deep-insights.js/issues/94
