### ISSUE TITLE
Widget form component

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6508]
### To be done:

- [x] Start using backbone-forms.
- [x] Create schema for each widget type (structure and specs).
- [x] Render all form attributes for each widget type (neither tab-pane nor stack-views, TBD).
- [x] If widget type changes, form should be recreated.
- [x] If widget type changes, widget definition model attributes should change, removing unnecessary properties for the new type. For example, 'bins' property within a Histogram is not necessary for Formula widget.
- [x] Generate formModel within widget definition model.
- [x] When widget type changes, remove widget definition model and create a new one.
- [x] When the widget definition form is edited, widget should be updated (This issue shold be done first -> https://github.com/CartoDB/deep-insights.js/issues/106).
- [x] Decide how and where to update the data of the select(s) when a previous one has changed?
   - Managed within each widget form model.
- [x] Improve saving of attributes from the widget form model to the widget def model.
   - Eg: `this.widgetDefinitionModel.saveAttributes(this.widgetFormModel.changed);`
   - Also, important to take into account the deep-insights widget update.
         - Eg: `this._widgetModel.update(changed);`
- [x] Review all "commented" specs + new ones.
- [x] Some widget attributes are not being updated in Deep-Insights widgets (https://github.com/CartoDB/deep-insights.js/pull/138). #6546
- [x] Make use of new table&user data models within widget form values -> #6551 
- [x] cast `sync_on_*_change` params to booleans, to be applied on widgets as expected

Branch: ```editor3-form-component```

**Comment by viddo** [comment]
For this component, I have some ideas that I'd like to discuss, perhaps later today?

For starters, I recommend reading http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/ and in particular _3. Extract Form Objects_. The article is intended for Ruby/Rails but I think the conceptual ideas can just be applied just as well on Backbone models and collections.

**Comment by xavijam** [comment]
Adding some documentation I'm finding:
- https://github.com/powmedia/backbone-forms

**Comment by xavijam** [comment]
A work on progress with @javierarce (TM)

**Comment by viddo** [comment]
@juanignaciosl was the assignment on purpose or a mistake? :sweat_smile:

**Comment by juanignaciosl** [comment]
I can't remember having assigned this (or anything) to you today, maybe my laptop was kidnapped :P

**Comment by xavijam** [comment]
Moving to @viddo and @javierarce.

**Comment by viddo** [comment]
closing, since was finished as part of merging #6561
