### ISSUE TITLE
[META] Improve error logging

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6752]
- [x] Update Rollbar gem (#6777).
- [x] Create new logging wrapper (#6778)
- [x] Fix poor error logging. Errors that...
  - ... don't provide context.
  - ... don't take advantage of Rollbar detail view.
  - ... group incorrectly at Rollbar.
  - ... are false negatives (not actual errors).
- [x] Remove direct Rollbar calls (#6611)

**Comment by javitonino** [comment]
I have been researching the new Rollbar gem. I have been going over the changelog and the methods we use to report exceptions are deprecated (but not gone yet) in the newer versions.

Everything appears to be working in the latest (2.8.0) version, although more testing is needed and we get a lot of deprecation notices.

The [newer alternative](https://github.com/rollbar/rollbar-gem#caught-exceptions-and-messages) is much nicer:
- Allows reporting exception and message (specially useful for grouping)
- Automatically adds user and request data
- Allows any extra data
- Easy logging levels: Rollbar.debug(), Rollbar.info(), etc.

With that in mind, proposed plan for this meta:
1. Update rollbar gem
2. Add a wrapper for new rollbar functions? Probably fine that we use the new Rollbar functions directly, as they seem to have everything we needed to create the wrappers for.
3. New code uses new functions
4. Start updating old code to use new wrappers. Prioritize reports without context or that group incorrectly. We should also consider [Rollbar grouping rules](https://rollbar.com/docs/custom-grouping/).
5. Remove deprecated Rollbar calls and wrappers

Thoughts? @juanignaciosl @gfiorav

**Comment by juanignaciosl** [comment]
I mostly agree:

1.- Ok.
2.- Not sure about what you mean. We should keep using wrapper methods, we don't want Rollbar all around the project, hiding it behind wrappers is much better. 
3.- Depending on the mismatch. If new wrappers are useful, let's use them. Taking advantage of new gem features using the same wrappers would be a win, but I don't know if it's convenient or feasible. Maybe when we see the code we can discuss better.
4.- Not sure about what you mean. If you mean "rewrite current wrapper calls to use the new wrappers" I wouldn't do it. It's a HUGE task. Id' focus on the most frequent errors.
5.- Ok about the gem, wrappers depend on previous comments.

Please keep the PRs as small as possible :_).

**Comment by juanignaciosl** [comment]
Related to #6611.
