### ISSUE TITLE
[META] Transition all invalidations from X-Cache-Channel to Surrogate-Key

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#6774]
We are transitioning cache handling from the X-Cache-Channel header to Surrogate-Key hash-keys as the documented here:
https://github.com/CartoDB/cartodb/wiki/CartoDB-Surrogate-Keys

This encompasses, for table caching:
- Node applications should emit and invalidate Surrogate-Keys:
  - [x] https://github.com/CartoDB/CartoDB-SQL-API/pull/273
  - [x] https://github.com/CartoDB/Windshaft-cartodb/pull/388
  - [x] https://github.com/CartoDB/node-cartodb-invalidation-service/pull/16
- [x] #6621, #6674 for removing direct table calls from Rails and delegate that responsibility to the Varnish trigger on the database
- [x] https://github.com/CartoDB/cartodb-postgresql/pull/204 as a dependency to fix proper Surrogate-Key invalidation tagging
- [x] #6773 to make Rails-installed invalidation triggers use Surrogate-Keys

For vizjson/rails caching:
- [ ] #6772 to make the only invalidations that have to be done from Rails use Surrogate-Keys

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
