### ISSUE TITLE
Implement analysis layers

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6780]
This is a meta/parent issue for all scope related to the new layers:

An user should be able to:
- See layers in correct order
- See analysis nodes
- Each layer should have a letter+color representation
- Each analysis node should have a letter+color (matching its layer) + order representation
- CRUD layers through the dev console (in lieu of UI for now)
- Drag-drop interactions, i.e. change order, create analysis etc.

---

**TODOs**
- [x] layers + analysis views #6821
- [x] persist layers+analysis state in backend #6827
- [x] fix translation namespaces (e.g. group top-level tab-panel labels together) #6831
- [x] implement "composite" view (render two source models, e.g. point-in-polygon) #6878

**Comment by viddo** [comment]
#6878
