### ISSUE TITLE
Add validation references for analyses structure

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6856]
This issue aggregates validations that will be convenient. They won't be implemented until we have an stable solution.
- [ ] ~~One analysis should not refer to another analysis node which has another dependent node.~~ (see @viddo comment).
- [ ] One analyses should only refer to head nodes.
- [X] Analysis ids can't be duplicated for the same visualization. In case of duplication, keep the newest. #8764
- [X] `widgets.source_id` --> Analysis natural id (https://github.com/CartoDB/cartodb/pull/8873).
- [X] `widgets.source_id` not nullable. If we had to support _legacy new maps_ this would be hard ((https://github.com/CartoDB/cartodb/pull/8873).
- [ ] Validate geometry type if stored (see #8760).

Related to #6751 .

cc @viddo @xavijam @javierarce @alonsogarciapablo

**Comment by viddo** [comment]
>  One analysis should not refer to another analysis node which has another dependent node.

This would be conflicting with how the frontend is currently implemented, right now there's one analysis persisted per layer (to KISS implementation of the remove-layer and drag'n'drop-analysis-to-create-layer user actions).

**Comment by gfiorav** [comment]
Regarding the validation:

```
widget.source_id -> analysis natural id
```

I guess kind of issue would create that is:

1. Frontend error is sending null source_id due to an error.
2. Frontend is sending a outdated source_id due to timing issues.

I'll just respond with normal API validation issues. The front is already listening for feedback right? If not we'll end up in an unsynced back/front state for sure!

**Comment by viddo** [comment]
> 2. Frontend is sending a outdated source_id due to timing issues.

In what scenarios would the source_id be considered "outdated"?

**Comment by gfiorav** [comment]
The request to create a widget arrives when the node it refers to has already been deleted. That could happen right? (Albeit it's rare)

**Comment by viddo** [comment]
Technically yes, although should not be doable from the UI. But probably a
good thing to have yes.

On Thursday, July 14, 2016, Guido Fioravantti <notifications@github.com>
wrote:

> The request to create a widget arrives when the node it refers to has
> already been deleted. That could happen right? (Albeit it's rare)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6856#issuecomment-232601841>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA7uHdjli-LNbUfGsswZ-D6H-rIjQgBmks5qVfSegaJpZM4Hu1ox>
> .
>


-- 

*Nicklas Gummesson*, software engineer
*CartoDB* — Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by gfiorav** [comment]
Yeah, it wouldn't be expected behaviour: internet is best effort, there's no way to guarantee order!

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
