### ISSUE TITLE
Edit/remove an analysis

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6859]
### TODOs:
- [x] When a layer analysis is clicked, it should open layer-analysis tab pane.
- [x] If a analysis is clicked (within analysis form), it should refresh the form and show those new properties.
- [x] Add `buffer` and `trade-area` analysis forms.
- [x] Add "Remove an analysis" option.
- [x] Keep using i18n labels.
- [x] Update analysis when any form value has changed.
- [x] If an analysis is clicked, next step should show analysis form with that clicked node as selected.
- [x] ~~Add `moran` and `point-in-polygon` analysis forms~~   (https://github.com/CartoDB/cartodb/issues/6948).

##### Nice to have:
- [x] Create "add analysis" buttons.
- [x] Add styles in the analysis workflow block (cc @piensaenpixel).
- [x] ~~Delete analysis confirmation "block"~~. -> To be completed when https://github.com/CartoDB/cartodb/issues/6929 is tackled.

**Comment by xavijam** [comment]
Branch: issue-6859
