### ISSUE TITLE
Add FK from visualization to permissions

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#7013]
We want to add this FK as some bugs could have been prevented by it (see https://github.com/CartoDB/cartodb-management/issues/4410).

It is a bit problematic, as the permissions have a reference back to the visualization. The plan to remove it is:
- [x] Add permissions for visualizations missing them. Check that all `viz.permission_id` fields are valid. PR #7015
- [x] Remove usage of `entity_id` and `entity_type` in the code. PR #7014
- [x] Ensure code works with the FK. PR #7029 
- [x] Migration: Add non-null FK in `viz.permission_id` PR #7030
- [x] Migration: Drop the `entity_*` columns from permissions. (last step, as it cannot be rolled back)
- [x] Cleanup: Remove `entity_*` methods from Carto::Visualization, and rake to delete unused permissions.
