### ISSUE TITLE
Styles for new editor (v1)

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7317]
- [x] Don't allow select animated sub-form if there is already a torque layer.
- [x] Unselect labels or animated subforms when any of those is selected.
- [x] Decide what to do with select components (animation column, labels column) without a default value choosen. -> _No value by default_
- [x] Nested forms. -> _no backbone nested forms_
  - [x] Tests for `Nested-model`.
  - [x] Tests for `Enabler` editor.
  - [x] Tests for `Field` component.
- [x] Start using fill component (https://github.com/CartoDB/cartodb/issues/7238).
- [x] Make sure style components are re-rendered when:
   - [x] Node schema changes.
   - [x] Node is added/removed to the stack (After #7334 is done).
- [x] None state should not render any component (adding message?).
- [x] Don't save style-properties definition if there is a property `autogenerated` within styleModel as true (cc @juanignaciosl).
- [x] ~~Fixes over custom-select list (down/up arrow bindings)~~ -> https://github.com/CartoDB/cartodb/issues/7327.
- [x] ~~Fixes over custom-carousel (selected item, shadows on scroll, etc...)~~ -> https://github.com/CartoDB/cartodb/issues/7328.
- [x] Implement aggregation component (COUNT, AVG, MIN, MAX,...) -> #7358.

**Comment by xavijam** [comment]
Closing this one and keep going in the rest.
