### ISSUE TITLE
Layer management

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7342]
- [x] Adding new layers:
  - [x] Add an empty layer CartoDB instead of cloning the one at the top.
  - [x] Make sure layer is added below the layer with labels.
- [x] Deleting an existing layer:
  - [x] Display "Delete layer..." in contextual menu.
  - [x] Do not display "Delete layer..." if there's only one "CartoDB" or "Torque" layer.
  - [x] Clicking "delete layer" deletes the layer:
    - [x] Layer is removed from the map (CartoDB.js).
    - [x] Layer deletion is persisted in the DB.
    - [x] Analysis nodes owned by the layer are deleted.
  - [x] Confirm deletion via Infobox.
- [x] Moving layers:
  - [x] Layers can be drag & dropped.
  - [x] After a layer is moved, the map is refreshed.
  - [x] After a layer is moved, new order of layers is persisted in the DB.
  - [x] Before saving the layers, create analysis definitions in the DB.
  - [x] If Context Menu is visible, hide it right when dragging starts.
  - [x] "CartoDB" and "Torque" layers can't be moved below the basemap.
  - [x] "CartoDB" and "Torque" layers can't be moved above the layer with labels.
  - [ ] ~~Animated layers should be on top~~ (see https://github.com/CartoDB/cartodb/issues/8975)
- [x] Other stuff:
  - [x] Expanding and collapsing layers
  - [x] Showing / hidding layers
  - [x] Apply a new color to the icon of new layers. (dupe of #7436 ?)
  - [x] Display labels layer differently (currently says Basemap).
  - [x] Basemap icon (preview).
  - [x] Renaming layers
  - [ ] ~~Indicate geometry output on layer avatar~~ (see https://github.com/CartoDB/cartodb/issues/7490)

**Comment by viddo** [comment]
Saw this issue after created #7479, perhaps you'd want to add to "Adding new layers" to keep track of it too?

**Comment by viddo** [comment]
Another thing I encounter, this one related to "moving layers", the order of the layers is not matching between editor and the map:

```js
> layerDefinitionsCollection.pluck('table_name')
["madrid_oct_2015_listings_with_closest_metro", "paradas_metro_madrid", "barrios", undefined]
> layerDefinitionsCollection.pluck('order')
[1, 1, 1, 0]

> vis._layersCollection.pluck('layer_name')
[undefined, "madrid_oct_2015_listings_with_closest_metro", "paradas_metro_madrid", "barrios"]
> vis._layersCollection.pluck('order')
[0, 1, 1, 1]
```

In the editor the layers are [ordered in the layer-definitions-collection according to the `order` attr](https://github.com/CartoDB/cartodb/blob/3713e29c7232194146907c1ec9205105abaf0747/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L26-L28).

Also, this is a fresh vis created from 3 selected datasets on the dashboard, so that would explain why the order values are all 1 I guess… not sure if we could/should fix that on the old editor or on the backend first.

**Comment by alonsogarciapablo** [comment]
I opened separate issues for the remaining work. Closing this "monster".
