### ISSUE TITLE
New styles part issues

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7413]
### Bugs
- [x] When a aggregation type is selected, if you refresh the editor, the styles doesn't appear anymore (maybe related with query wrapper) (@javisantana).
- [x] When we reset styles, we don't reset layer type (it stays for example with torque :S) (@xavijam).
- [x] Fetching labels for select component are not present (unfetched, fetching, error, etc...) (@xavijam).
- [x] Aggregation value component is not doing anything (@javisantana).
- [x] Remove all component delays/debounces, controlled via style form models (@xavijam).
- [x] Number input should not trigger a change event when figure is `X.` .
- [x] After changing aggregation size a little bit, tiler throws an error about `Error creating the map instance on Windshaft: syntax error at or near ")"` (@javisantana).
- [x] After selecting a column and a color ramp (in stroke component), category style is not applied for lines (@javisantana).
- [x] Is it possible to use a size range for lines?. Tried but not working (@javisantana).
- [x] Disable labels for heatmap style (not possible to add layers for torque layers) (@xavijam).
- [x] When a new layer is added (not imported), you can't change styles (js error) (#7465 @xavijam). 
- ~~Lines and polygons datasets can only use simple styles (aggregations only working for points)~~ (@saleiva @urbanphes).
- [x] Implement Heatmap (@javisantana).
- [x] Last Maps API changes doesn't work in the current styles (test with a choropleth) (#7485 @javisantana).
- [x] Heatmap animated column #7530 (@xavijam).
- [x] Editing an stroke fails. Set the stroke, open the map again, and try to edit. You'll get: `Uncaught Error: TrackJS Caught: a.isEditing is not a function` (@xavijam).
- [x] Administrative regions style is not working after being selected (#7329 @javisantana). https://github.com/CartoDB/cartodb/pull/7559
- [x] Add proper adm. region datasets available in production (@rafatower).
- [x] If a heatmap type is selected, and then you select another type (simple for example), layer doesn't render anything (@javisantana). -> https://github.com/CartoDB/cartodb.js/commit/05da7417a2d6045781f9f014ea2cfa5d57ddfdb1
- [x] Start using categories with turbo-carto and implement the way to change them in the fill component (@javierarce @javisantana) -> It will require changes in the wizards migration cc @juanignaciosl. -> https://github.com/CartoDB/cartodb/pull/7624.

### Pending
- [x] Loading state is not implemented (designed as placeholder state) (@xavijam).
- [x] Add CartoCSS editor (https://github.com/CartoDB/cartodb/issues/7445 @nobuti).
- [x] Apply CartoCSS styles (+ UnDo) (@xavijam).
- ~~Finish all pending stuff from #7317~~ (@xavijam) -> https://github.com/CartoDB/cartodb/issues/7547.

cc @javisantana

**Comment by saleiva** [comment]
About the aggregations in just points dataset, I don't agree. Polygons can be also aggregated. Think on Protected Areas per country for example. But if we need to prioritize, I'm happy to start just with points.

**Comment by xavijam** [comment]
We will check it @saleiva ^^^.
@javisantana, first point problem is still happening to me in production, did we forget to merge something?

**Comment by javisantana** [comment]
let's discuss about use cases for polygon aggregation

**Comment by xavijam** [comment]
Closing this ticket, new bugs or features should be placed in new tickets. 💋
