### ISSUE TITLE
Fill component fixes

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#8536]
Issue to keep track of all the fill component fixes: 

- [x] Remove switch to transform ramps to categories in the fill component #8534
- [x] Move Quantiles method to the block on top so we gain some space #8525 
- [x] Pass option to hide or disable opacity #7740
- [x] Switching to string a column from a numeric one shows the switcher #8547
- [x] Remove switch to transform categories to ramps in the fill component #8540

Current branch: `fill-fixes`

**Comment by saleiva** [comment]
hey @javierarce 
The issue with the opacity input not sending the value is still happening. Is there any ticket? I couldn't find it :(

**Comment by saleiva** [comment]
It's happening the same with the hex values
