### ISSUE TITLE
Email redesign

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8889]
Update the design of the emails.

Design: #9068

- [x] Transitory solution: change logos @MariaCheca 
- [x] Invite user to organization #8214
- [x] Review share dataset email #8939
- [x] Review share map email #8940
- [x] Review unshare dataset mail #8941
- [x] Review unshare map mail #9228
- [x] Review liked map email #8944
- [x] Review liked dataset email #8945 
- [x] Review trending map mail #8946 
- [x] Review geocoding finished email #8933 
- [x] Review import finished email #8934
- [x] Review sync maximum number of retries issue email #8937
- [x] Review new organization user email #8938
- [x] Review organization quota reached email #8935
- [x] Review organization seat limit reached email #8936

**Comment by juanignaciosl** [comment]
@urbanphes this list should be the full list of emails sent from a CartoDB instance.

**Comment by saleiva** [comment]
Assigning to @urbanphes. Feel free to reasign to @juanignaciosl when having more visibility about the new emails

**Comment by MariaCheca** [comment]
cartodb project mails redesigned.
