### ISSUE TITLE
Write "on boarding" texts analyses

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9034]
We need to have text for the screens that appear after a analysis has been performed.

The text shown in each of these screens should inform the users about the changes that the analyses have produce in the dataset and some indications on what can be done with the new fields.

![screen shot 2016-07-20 at 19 20 35](https://cloud.githubusercontent.com/assets/4933/16995904/0dc4cf28-4eaf-11e6-8280-072bcaa1dff3.png)

Here's a list of tickets for the analyses we have implemented so far, so we can track the work done on each of them:

- [x] Georeference #9021 
- [x] Enrich from data observatory #9022 
- [x] Join columns from 2nd layer #9023
- [x] Filter by layer #9024
- [x] Find centroid #9025
- [x] Area of influence #9026
- [x] Intersect second layer #9027 
- [x] Filter point in polygons #9028
- [x] Filter rows by column value #9029
- [x] Subsample percent of rows #9030
- [x] Calculate clusters of points #9031
- [x] Detect outliers and clusters #9032
- [x] Predict trends and volatility #9033

It would probably make sense to have a generic text we could show for new analysis that don't have an specific onw, in case we always want to show something.

**Comment by saleiva** [comment]
Hey @ohasselblad @stuartlynn sorry on the short notice, but we're very close to have this done and we are lacking the texts for each of them. Can you guys provide us those? @javierarce created a ticket for every of the analysis we have now.

**Comment by saleiva** [comment]
Ah! we are planning to have this done before EOW

**Comment by andrewxhill** [comment]
What are the constraints here? 
Sections of text needed and then Words #, Line # for each

**Comment by saleiva** [comment]
Well, if you take a look at the designs, you will see we have limited space. I'd say that in general we should go with the shortest possible version. Anyway, when implementing those we will learn more about the constraints

**Comment by ohasselblad** [comment]
DONE, thanks guys, I learned lots more about the builder doing this.

**Comment by javierarce** [comment]
Thanks a lot @ohasselblad, @andrewxhill, and @saleiva! ❤️
