### ISSUE TITLE
Start applying enabler editor

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9070]
After adding [enabler-editor component](https://github.com/CartoDB/cartodb/pull/9040) to backbone forms, we should use it wherever we have optional inputs.

- [x] Moran denominator. (#8771)
- [x] Widget form, suffix and prefix. (#9258)
- [x] Centroid model (and behaviour + test). (#9378)
- [x] Geocoding (Named places): Admin region and Country (#9381)
- [x] Geocoding (Admin region): Country (#9381)
- [x] Geocoding (Postal codes): Country (#9381)
- [x] Geocoding (Street Addesses): City, state, country (#9381)

**Comment by xavijam** [comment]
cc @saleiva

**Comment by saleiva** [comment]
Added a few :)

**Comment by xavijam** [comment]
Perfect, thanks @saleiva.

**Comment by saleiva** [comment]
The general rule should be that for every optional value, we use this component.

**Comment by xavijam** [comment]
Agree, adding @viddo and @javierarce ^^^ for this rule :).

**Comment by nobuti** [comment]
All forms above have been updated. Looking for more cases.

**Comment by xavijam** [comment]
Let's close it, if we find new ones we will open a new ticket 💋
