### ISSUE TITLE
Connectors API revamp

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#9572]
## Current (alpha) API

At the moment the connector imports/synchronizations have a `connector` parameter which contains these subparameters:

* `connection` : parameters which defined the connection and which currently
  are the odbc connection string attributes, including the `driver` name.
  These parameters vary from driver to driver.
* `schema` : remote schema name
* `table` : table to be imported
* `sql_query` : optional query that defines dataset to be imported (as `table`)
* `sql_count` : optional query to compute dataset size
* `encoding` : optional character encoding

### Example:

```json
"connector" : {
  "connection" : {
    "driver" : "PostgreSQL Unicode",
    "SERVER" : "the-server-address",
    "DATABASE" : "the-database",
    "UID" : "the-user",
    "PWD" : "the-password"
  },
  "schema" : "public",
  "table"  : "external_table"
}
```

### Problems

This current situation has the problem of exposing the internal detail that we're using ODBC and
requires the user to know about the particular drivers used to be able to choose the correct parameters.

As we have no information in the importer code regarding the valid drivers and parameters,
the UI would need to take on that responsibility (or either let the user enter arbitrary
parameters).

## New (beta) API

We'll determine which parameters are exposed for each data source, maintaining consistency in the available parameters and their name. We'll use provider classes that will handle the details of generating the datasource connection strings/attributes (odbc or otherwise)-

We'll keep `connector` as a parameter containing all the connector sub-parameters.
A new parameter `provider` will be added inside the `connector` parameter. This identifies our provider (a class derived from Provider). The rest of the admitted `connector` parameters will depend on the provider class.

Initial provider available will be: `mysql` `postgresql` `sqlserver` `hive`. They're all odbc_fdw-based providers and have these parameters in common (as now):  `schema`, `table`, `sql_query`, `sql_count`, `encoding`

Each has additional parameters but they're all consistently named, such as `server`, `port`, `database`, `username`, `password`. (so avoid current variations such as server/host/address...)

This will make it easy to define new providers, either using ODBC or based on different FDWs.

### Example:

```json
"connector" : {
  "provider" : "postgresql",
  "server"   : "the-server-address",
  "database" : "the-database",
  "username" : "the-user",
  "password" : "the-password",
  "schema"   : "public",
  "table"    : "external_table"
}
```

### Generic ODBC provider

By having provider='odbc' a generic ODBC provider can used, which allows testing new drivers, new user requirements (e.g. auth parameters), etc.

This provider allows any odbc attribute through a 'connection' parameter (just as now).

We can make 'odbc' the default value for `provider` to avoid breaking existing synchronizations.

This provider would not be exposed through the UI.

### Example of Provider definition

With this approach, defining new odbc providers is a matter of redefining a few methods in a derived class which define the accepted parameters and the mapping to the internal connection attributes, for example:

```ruby
class Connector
  # MySQL provider using this driver: http://dev.mysql.com/doc/connector-odbc/en/
  class MySqlProvider < OdbcProvider
    private

    def fixed_connection_attributes
      {
        Driver:   'MySQL',
        option:   0,
        prefetch: 0,
        no_ssps:  0,
        can_handle_exp_pwd: 0
      }
    end

    def required_connection_attributes
      {
        username: :uid,
        password: :pwd,
        server:   :server
      }
    end

    def optional_connection_attributes
      {
        port: { port: 3306 },
        database: { database: nil }
      }
    end

    def non_connection_parameters
      # The schema should default to the database name
      super.reverse_merge('schema' => Support.fetch_ignoring_case(@params, 'database'))
    end

  end
end

```

## Tasks

- [ ] Refactor `Connector` to use Providers, each defining the valid parameters
- [ ] Implement base class for odbc_fdw providers
- [ ] Implement providers currently supported odbc sources: MySQL, PostgreSQL, SQL Server and Hive.
- [ ] Write unit tests for `Connector` class to test expected SQL generated by each provider (but avoiding real connections to the database)
- [ ] Document the new API
- [ ] Add UI-supporting functionality to the providers
- [ ] Implement postgresql-fdw provider

**Comment by jgoizueta** [comment]
cc @ethervoid @rafatower @javisantana

**Comment by ethervoid** [comment]
I'll add one more check `Define limits for the connectors`

**Comment by jgoizueta** [comment]
That's in our backlog after this API revamp. should we add it here?

**Comment by ethervoid** [comment]
Ok, don't add it then :)

**Comment by javisantana** [comment]
Some comments:

- The fact that we have connection parameters in a different object does not mean we use ODBC. I feel good about having the common things in a place and the other stuff that depends on the conector, in a different one, like:

```
{
type: 'mysql'
connection: { user, pass ..., database: '....'}
table: '....'
sql: '...'
}
```

- The limits should be really present at api level when possible, at least at documentation level. For example when you have rate-limit is a common practice to have a header with rate limits

**Comment by jgoizueta** [comment]
Closing this as we're using a doc to collaborate on the API design before taking on the implementation.

**Comment by javisantana** [comment]
@jgoizueta could you point to the document here?
