### ISSUE TITLE
Add Voronoi analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9885]
![screen shot 2016-09-26 at 15 28 52](https://cloud.githubusercontent.com/assets/4933/18848765/d912ba86-83fd-11e6-830e-94f674b9ba9b.png)
### TODO:
- [ ] Description for the add analysis window
- [ ] [Implemented voronoi analysis](https://github.com/CartoDB/camshaft/pull/177)
- [ ] [Onboarding texts](https://github.com/CartoDB/cartodb/issues/9890)
- [x] [Design animation for this analysis](https://github.com/CartoDB/design/issues/240)

**Comment by javierarce** [comment]
Ok, this is going to be on hold for a while…


![image](https://cloud.githubusercontent.com/assets/4933/18884501/a2af6530-84b5-11e6-9f46-24d0f656b7fb.png)

**Comment by urbanphes** [comment]
The designs are here https://github.com/CartoDB/design/issues/240

**Comment by saleiva** [comment]
More info at https://github.com/CartoDB/design/issues/444#issuecomment-268040903
